### ISSUE TITLE
Look like we have the same model , with just 1 CRC at end :

### ISSUE THREAD

**Issue by sigmounte** [salvamr/m365-ble-msg-builder#3]
Hello , here is what i decoded : ( don't mind the Buff:55 at end ) 

do you have the rest of the protocol ? Seem like i have a different protocol, mine only use FF/FE has a CRC ?

I'm not interested in the lock / unlock ( i don't have a password on mine ) , just the engine start / stop ? Could you help ?

Thanks a lot ! 

Applying power i get this : 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x1C 0x13 0x00 0x00 0x40 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x00 0x01 0x6F ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:04(0x04)  BLE->ESC Write(0x03) Datas: [0x7C 0x00 0x00 0x5C ] CRC:FF Buff:55 
0x55-0xAA  Length:15(0x0F)  Direction?:24 Read(0x01) Datas: [0x00 0x4D 0x49 0x53 0x63 0x6F 0x6F 0x74 0x65 0x72 0x34 0x33 0x31 0x31 0x8D ] CRC:FB Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x00 0x01 0x6F ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE4 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ] CRC:FC Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0x25 0x16 0x02 0x26 0x26 0xEF ] CRC:FE Buff:55 
0x55-0xAA  Length:24(0x18)  ESC->BLE Read(0x01) Datas: [0x25 0xBE 0x05 0x00 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xDE ] CRC:FD Buff:55 
0x55-0xAA  Length:04(0x04)  BLE->ESC Write(0x03) Datas: [0x70 0x01 0x00 0x67 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x00 0x01 0x6F ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0x10 0x1E 0x02 0x26 0x26 0xFC ] CRC:FE Buff:55 
0x55-0xAA  Length:32(0x20)  ESC->BLE Read(0x01) Datas: [0x10 0x31 0x36 0x31 0x33 0x32 0x2F 0x30 0x30 0x30 0x37 0x35 0x35 0x31 0x34 0x30 0x30 0x30 0x30 0x30 0x30 0x38 0x01 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x8E ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x00 0x01 0x6F ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0x10 0x1E 0x02 0x26 0x26 0xFC ] CRC:FE Buff:55 
0x55-0xAA  Length:32(0x20)  ESC->BLE Read(0x01) Datas: [0x10 0x31 0x36 0x31 0x33 0x32 0x2F 0x30 0x30 0x30 0x37 0x35 0x35 0x31 0x34 0x30 0x30 0x30 0x30 0x30 0x30 0x38 0x01 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x8E ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE5 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFF ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE6 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFE ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE6 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFE ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE6 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFE ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE6 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFE ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE6 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFE ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE6 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFE ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:09(0x09)  BLE->ESC Read(0x64) Datas: [0x00 0x06 0x26 0x26 0x00 0x00 0x68 0x00 0xB8 ] CRC:FE Buff:55 
0x55-0xAA  Length:06(0x06)  ESC->BLE Read(0x64) Datas: [0x00 0x00 0x04 0x64 0x01 0x0B ] CRC:FF Buff:55 
0x55-0xAA  Length:06(0x06)  BLE->ESC R/W?:61 Datas: [0xB0 0x20 0x02 0x26 0x26 0x5A ] CRC:FE Buff:55 
0x55-0xAA  Length:34(0x22)  ESC->BLE Read(0x01) Datas: [0xB0 0x00 0x00 0x00 0x00 0x02 0x00 0x00 0x00 0x31 0x00 0x00 0x00 0x00 0x00 0xB5 0x47 0x01 0x00 0x00 0x00 0xE6 0x05 0xF0 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0xFE ] CRC:FB Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:55 
0x55-0xAA  Length:07(0x07)  BLE->ESC Write(0x65) Datas: [0x00 0x04 0x26 0x26 0x00 0x00 0x23 ] CRC:FF Buff:00 Buff:00

**Comment by salvamr** [comment]
I'm sorry but I'm not into reverse engineering the protocol. You could ask Camilo directly through his repo here https://github.com/CamiAlfa/M365-BLE-PROTOCOL
