### ISSUE TITLE
BLE 81 compatibility

### ISSUE THREAD

**Issue by mrmrmrmr1** [salvamr/m365-ble-msg-builder#4]
Hi,

We know that there is a BLE communication change between BLE fw 72 and BLE fw 81.
Does this code work with 81 ?
I see several 3rd party apps that can run with BLE 81 , so it is achievable I guess.
But what is the difference between 72 and 81.
Does anyone know ?

thanks.

**Comment by mrmrmrmr1** [comment]
please,  I just need help. Some apps on Play store are detecting the BLE version as 81 and asking user to reconnect. I assume it is not just a reconnection. How should  we make the connection to BLE 81.

**Comment by salvamr** [comment]
Hi @mrmrmrmr1 

Sorry I'm not in to modifying the scooter anymore so I don't know how the new BLE firmware works, probably the same, as you mention. You can try to ask Camilo (@CamiAlfa in telegram) for more info.
